export const fountainBg = {
  "fountain.look.jammed": "Вода до фонтана има. Кранът обаче е ръждясал и заял. Старците на пейката сигурно помнят кога последно се е въртял.",
  "fountain.look.oiled": "Олиото е попило около крана. Остава да го завъртя — с „Използвай“ върху фонтана.",
  "fountain.look.repaired": "Тънка струйка, но истинска. Не е нарисувана в отчета.",
  "fountain.use.jammed": "Кранът изскърца и не помръдна. Само със сила няма да стане. Ще питам старците на пейката.",
  "fountain.use.hint": "Трябва да смажа крана с олио от механата. Ако съм го изпил, Киро ще даде друго; ако съм го оставил някъде, ще си го прибера.",
  "fountain.use.repaired": "Завъртях крана. Потече! Малко, но без тържествено откриване. Да кажа на Баба Стоянка.",
  "fountain.use.already": "Работи. Няма да го спирам само за да го открия повторно.",
  "fountain.oil.applied": "Смазах заялия кран. Сега мога да го завъртя — „Използвай“ върху фонтана.",
  "fountain.oil.already": "Кранът вече е смазан. Повече олио ще превърне ремонта в салата.",
  "fountain.wrong_liquid": "На крана му трябва смазване, не почерпка. Олиото от механата ще свърши работа.",
  "fountain.chorus.clue": "Старците: Вода има, кранът е заял. В общината скърцането го водят частична дейност. Капни олио от механата и го завърти.",
  "fountain.chorus.oiled": "Старците: Смазал си го. Сега го завърти. Ние ще наблюдаваме — имаме стаж.",
  "fountain.chorus.repaired": "Старците: Потече. Запиши датата, преди някой да запише заслугата.",
  "fountain.baba.terms": "Баба Стоянка: Не ми обещавай пет години. Оправи нещо за пет минути. Виж фонтана, после питай старците на пейката.",
  "fountain.baba.tradition": "Баба Стоянка: По традиция обещавате. Ти вземи наруши традицията — оправи фонтана.",
  "fountain.baba.promise": "Баба Стоянка: Като потече вода, ще говорим. Обещанията ми пълнят ушите, не чешмата.",
  "fountain.baba.oil": "Баба Стоянка: Не на мен, на заялия кран! Смажи го с олиото, пусни фонтана и тогава ела.",
  "fountain.baba.no_gifts": "Баба Стоянка: Прибери си го. Искам работещ фонтан, не пълна торба. И старите ни караници няма да го поправят.",
  "fountain.baba.choice.report": "Фонтанът вече работи. Ела да видиш.",
  "fountain.baba.support": "Баба Стоянка: Не е много вода. Ама е повече от обещание. Имаш гласа ми.",
  "fountain.baba.confirmed": "Баба Стоянка: Дала съм си думата. Не ме карай да я заверявам всеки път.",
  "fountain.kiro.choice.refill": "Дай ми 200 мл олио и ги пиши на сметката ми.",
  "fountain.kiro.choice.hint": "Откъде да взема олио за ремонта?",
  "fountain.kiro.refill": "Киро: Ето резервна бутилка. За крана, Митко. Той скърца, не ти.",
  "fountain.kiro.hint": "Киро: На шкафа има олио. Ако си го изпил, ще дам друго. Ако си го оставил на земята, прибери си го — не е изчезнало по процедура.",
  "fountain.quest.ask": "Попитай Баба Стоянка как да спечелиш подкрепата ѝ.",
  "fountain.quest.inspect": "Огледай счупения фонтан на площада.",
  "fountain.quest.chorus": "Попитай старците на пейката за заялия кран.",
  "fountain.quest.find_oil": "Вземи олио от механата. Ако е изпито, поискай друго от Киро; ако е оставено, прибери го.",
  "fountain.quest.oil": "Използвай олиото върху фонтана, за да смажеш крана.",
  "fountain.quest.operate": "Използвай фонтана, за да завъртиш смазания кран.",
  "fountain.quest.report": "Кажи на Баба Стоянка, че фонтанът работи."
};

export const fountainEn = {
  "fountain.look.jammed": "Water reaches the fountain, but the valve is rusted shut. The old men on the bench might remember when it last turned.",
  "fountain.look.oiled": "The oil has worked into the valve. Now turn it: choose Use on the fountain.",
  "fountain.look.repaired": "A thin stream, but a real one. It doesn't just exist in the report.",
  "fountain.use.jammed": "The valve squeaked and stayed put. Force won't do it. I'll ask the old men on the bench.",
  "fountain.use.hint": "The valve needs cooking oil from the Mehana. Kiro can replace oil I've drunk; if I dropped it, I should pick it up.",
  "fountain.use.repaired": "I turned the valve. Water! Not much, but no opening ceremony required. I'll tell Baba Stoyanka.",
  "fountain.use.already": "It works. I'm not shutting it off just to hold another grand opening.",
  "fountain.oil.applied": "The stuck valve is oiled. Now choose Use on the fountain to turn it.",
  "fountain.oil.already": "The valve is already oiled. Any more and this repair becomes a salad.",
  "fountain.wrong_liquid": "The valve needs lubrication, not hospitality. Cooking oil from the Mehana should do it.",
  "fountain.chorus.clue": "Old Men: Water's there. Valve's stuck. The municipality counts the squeaking as partial operation. Oil it with cooking oil from the Mehana, then turn it.",
  "fountain.chorus.oiled": "Old Men: You've oiled it. Now turn it. We'll supervise. Years of experience.",
  "fountain.chorus.repaired": "Old Men: Water. Record the date before someone else records the credit.",
  "fountain.baba.terms": "Baba Stoyanka: Don't promise me five years. Fix something in five minutes. Look at the fountain, then ask the old men on the bench.",
  "fountain.baba.tradition": "Baba Stoyanka: Promises are traditional. Break with tradition. Fix the fountain.",
  "fountain.baba.promise": "Baba Stoyanka: We'll talk when the water flows. Promises fill my ears, not the fountain.",
  "fountain.baba.oil": "Baba Stoyanka: Not for me—for the stuck valve! Oil it, get the fountain running, then come back.",
  "fountain.baba.no_gifts": "Baba Stoyanka: Keep it. I want a working fountain, not a full shopping bag. Our old quarrels won't fix it either.",
  "fountain.baba.choice.report": "The fountain works now. Come and see.",
  "fountain.baba.support": "Baba Stoyanka: It isn't much water. But it's more than a promise. You have my vote.",
  "fountain.baba.confirmed": "Baba Stoyanka: I gave you my word. Stop asking me to notarize it.",
  "fountain.kiro.choice.refill": "Give me 200 ml of cooking oil and put it on my tab.",
  "fountain.kiro.choice.hint": "Where can I get oil for the repair?",
  "fountain.kiro.refill": "Kiro: Here's a spare bottle. For the valve, Mitko. It's the one squeaking.",
  "fountain.kiro.hint": "Kiro: There's oil on the sideboard. Drank it? I'll replace it. Dropped it? Pick it up. It hasn't vanished into the filing system.",
  "fountain.quest.ask": "Ask Baba Stoyanka how to earn her support.",
  "fountain.quest.inspect": "Inspect the broken fountain in the square.",
  "fountain.quest.chorus": "Ask the old men on the bench about the stuck valve.",
  "fountain.quest.find_oil": "Get oil from the Mehana. Ask Kiro for more if you drank it; retrieve it if you dropped it.",
  "fountain.quest.oil": "Use the cooking oil on the fountain to lubricate the valve.",
  "fountain.quest.operate": "Use the fountain to turn the oiled valve.",
  "fountain.quest.report": "Tell Baba Stoyanka the fountain is working."
};
