import { electionEn } from "./chapter1Election.js";
import { archiveEn } from "./chapter1Archive.js";
import { registrationEn } from "./chapter1Registration.js";
import { campaignEn } from "./chapter1Campaign.js";
import { fountainEn } from "./chapter1Fountain.js";

export const en = {
  "ui.received_oil.controls": "Click and drag to tilt the bottle. Scroll to zoom in and out.",
  "ui.received_oil.reset": "Front",
  "ui.received_oil.loading": "Loading bottle…",
  "ui.received_oil.unavailable": "3D view unavailable. Bottle illustration shown.",
  "ui.received_oil.itemTitle": "200 ml sunflower oil",
  "ui.received_oil.rotate": "Inspect the bottle",
  "ui.received_oil.left": "Turn left",
  "ui.received_oil.right": "Turn right",
  "ui.received_oil.up": "Turn up",
  "ui.received_oil.down": "Turn down",
  "ui.received_oil.rollLeft": "Tilt left",
  "ui.received_oil.rollRight": "Tilt right",
  "ui.received_oil.zoomIn": "Zoom in",
  "ui.received_oil.zoomOut": "Zoom out",
  "ui.received_oil.title": "Received",
  "ui.received_oil.description": "In a reused rakia bottle. Added to your tab.",
  "ui.received_oil.close": "Put away",

  "ui.sound.volume": "Volume",
  "ui.sound.on": "Sound: on",
  "ui.sound.off": "Sound: off",

  ...electionEn,
  ...archiveEn,
  ...registrationEn,
  ...campaignEn,
  ...fountainEn,
  "scene.chapter1.mayor_office.title": "Mayor’s Office",
  "exit.to_mayor_office": "Mayor’s Office",
  "office.mayor.name": "The Mayor",
  "office.mayor.look": "The Mayor, standing beside his desk.",
  "office.desk.name": "Mayor’s desk",
  "office.desk.look": "Official papers, a telephone and the Mayor’s stamp.",
  "game.title": "Comrade Candidate",
  "chapter1.title": "Election Day in the Village",
  "scene.chapter1.apartment.title": "Bai Mitko's Apartment",
  "scene.chapter1.village_square.title": "Village Square",
  "scene.chapter1.mehana.title": "Mehana \"The Two Goats\"",
  "scene.chapter1.municipality.title": "Municipality — Candidate Services",
  "scene.chapter1.election_booth.title": "Polling Station — Final Promises Room",

  "ui.new_game": "New Game",
  "ui.continue": "Continue",
  "ui.language": "Language",
  "ui.pause": "Pause",
  "ui.resume": "Resume",
  "ui.save": "Save",
  "ui.menu": "Menu",
  "ui.restart": "Restart",
  "ui.main_menu": "Main Menu",
  "ui.restart_confirm": "Restart Chapter 1 and clear the current save?",
  "ui.reset": "Reset",
  "ui.reset_confirm": "Reset the current game, pockets, and all saved inventory items?",
  "ui.quests": "Quests",
  "ui.quests.outstanding": "Outstanding: {count}",
  "ui.quests.none": "No outstanding quests.",
  "ui.quests.tab.outstanding": "Outstanding",
  "ui.quests.tab.completed": "Completed",
  "ui.quests.tab_with_count": "{tab}: {count}",
  "ui.quests.outstanding.none": "No outstanding quests.",
  "ui.quests.completed.none": "No completed quests yet.",
  "ui.hud": "Game status",
  "ui.inventory": "Inventory",
  "ui.inventory.use": "Use",
  "ui.inventory.use_on_self": "Use on Bai Mitko",
  "ui.inventory.inspect": "Inspect",
  "ui.inventory.drop": "Drop",
  "ui.inventory.close": "Close",
  "ui.inventory.cancel": "Cancel",
  "ui.inventory.use_prompt": "Use {item} with...",
  "ui.inventory.use_with_target": "Use {item} with {target}",
  "ui.dropped_items.title": "Left Nearby",
  "ui.dropped_items.pick_up": "Pick up",
  "ui.dropped_items.close": "Close",
  "ui.verb": "Verb",
  "ui.meter.influence": "Influence",
  "ui.meter.rakia": "Rakia glasses",
  "ui.intoxication.daisy": "Daisy",
  "ui.intoxication.merry": "Merry",
  "ui.intoxication.tipsy": "Tipsy",
  "ui.intoxication.plastered": "Plastered",
  "ui.meter.suspicion": "Suspicion",
  "ui.meter.public_mood": "Public Mood",
  "ui.hint": "Left click: act. Right click: change verb. Esc: pause.",
  "npc.bai_mitko.name": "Bai Mitko",

  "verb.look": "Look",
  "verb.talk": "Talk",
  "verb.use": "Use",
  "verb.take": "Take",

  "exit.to_village_square": "To Village Square",
  "exit.to_apartment": "To Apartment",
  "exit.to_mehana": "To Mehana",
  "exit.to_municipality": "To Municipality",
  "exit.to_election_booth": "To the Polling Station",

  "item.accordion.name": "Accordion",
  "item.accordion.desc": "The only thing Bai Mitko ever played honestly.",
  "item.unpaid_bills.name": "Unpaid Bills",
  "item.unpaid_bills.desc": "A financial autobiography with a tragic ending.",
  "msg.apartment.unpaid_bills_taken": "The bills are pocketed. Evidence does not stay on the table unless guests are coming.",
  "item.empty_envelope.name": "Empty Envelope",
  "item.empty_envelope.desc": "Empty, but administratively promising.",
  "item.fake_diploma.name": "Fake Diploma",
  "item.fake_diploma.desc": "Official enough for voters who squint.",
  "item.rakia.name": "Bottle of Rakia",
  "item.rakia.desc": "High-proof liquid democracy.",
  "item.shopska_salad.name": "Shopska Salad",
  "item.shopska_salad.desc": "Tomatoes, cucumbers, and enough grated cheese to conceal the fiscal policy.",
  "item.tripe_soup.name": "Takeaway Tripe Soup",
  "item.tripe_soup.desc": "Tripe soup in a jar. Emergency stabilization with a screw-top lid.",
  "item.village_wine.name": "Bottle of Village Wine",
  "item.village_wine.desc": "Homemade wine with enough character to pass for an official mediator.",
  "item.sunflower_oil.name": "Sunflower Oil",
  "item.sunflower_oil.desc": "Folk medicine for heavy political decisions.",
  "item.glass_of_water.name": "Glass of Water",
  "item.glass_of_water.desc": "Colorless, nonpartisan, and suspiciously sober.",
  "item.campaign_pamphlets.name": "Campaign Pamphlets",
  "item.campaign_pamphlets.desc": "Promises on thin paper.",
  "item.suspicious_receipt.name": "Suspicious Receipt",
  "item.suspicious_receipt.desc": "It says receipt. It smells like evidence.",
  "item.pickle_jar.name": "Pickle Jar",
  "item.pickle_jar.desc": "A preserved vegetable with a clearer platform than most candidates.",
  "item.ballot_box.name": "Ballot Box",
  "item.ballot_box.desc": "Transparent by law, cloudy by tradition.",
  "item.municipality_stamp.name": "Municipality Stamp",
  "item.municipality_stamp.desc": "A little stamp can open a big door.",

  "hotspot.wallpaper.name": "Peeling Wallpaper",
  "hotspot.window.name": "Window",
  "hotspot.campaign_poster.name": "Campaign Poster Draft",
  "hotspot.mirror.name": "Cracked Mirror",
  "hotspot.tv.name": "Old TV",
  "hotspot.wardrobe.name": "Wardrobe",
  "hotspot.table.name": "Cheap Table",
  "hotspot.poster_board.name": "Campaign Board",
  "hotspot.fountain.name": "Fountain",
  "hotspot.kiosk.name": "News Kiosk",
  "hotspot.statue.name": "Statue",
  "hotspot.old_men_bench.name": "Old Men Bench",
  "hotspot.election_notice.name": "Election Notice",
  "hotspot.square.mehana_menu.name": "Mehana Menu",
  "hotspot.dropped_items.name": "Dropped Belongings",
  "hotspot.water_jug.name": "Water Jug",
  "hotspot.mehana_table.name": "Mehana Table",
  "hotspot.mehana.bai_mitko_rakia_glass.name": "Bai Mitko's Rakia Glass",
  "hotspot.mehana.tony_rakia_glass.name": "Tony's Rakia Glass",
  "hotspot.mehana.cellar_hatch.name": "Cellar Hatch",
  "hotspot.mehana.newspaper.name": "Today's Newspaper",
  "hotspot.mehana.radio.name": "Old Radio",
  "hotspot.apartment.rakia_bottle.name": "Rakia Bottle",
  "hotspot.apartment.bed.name": "Sofa-bed",
  "hotspot.municipality.candidate_register.name": "Candidate Register",
  "hotspot.municipality.stamp_desk.name": "Stamp Desk",
  "hotspot.municipality.archive_cabinet.name": "Archive Cabinet",

  "npc.baba_stoyanka.name": "Baba Stoyanka",
  "npc.tony_fridge.name": "Tony the Fridge",
  "npc.mehana_waiter.name": "Waiter Kiro",
  "npc.municipality_clerk.name": "Clerk Penka",
  "npc.municipality_colleague.name": "The Colleague",
  "npc.municipality_background_clerk.name": "The Clerk",
  "npc.municipality_security_officer.name": "Duty Officer",
  "npc.journalist.name": "Ralitsa Microphonova",

  "look.apartment.wallpaper": "The wallpaper is peeling with the quiet dignity of a retired minister.",
  "look.apartment.window": "A window to fresh air, as far as the district allows.",
  "look.apartment.window.closed": "The window is closed. The fresh air is waiting outside for authorization.",
  "look.apartment.window.open": "The window is open. The fresh air is still deciding whether to come in.",
  "look.apartment.accordion": "My accordion. The only thing I ever played honestly.",
  "look.apartment.mirror": "The mirror shows him in three pieces. Coalition energy.",
  "look.apartment.tv": "The TV is explaining that the situation is stable, but in an emergency way.",
  "look.apartment.wardrobe": "The wardrobe guards clothes from a time when Bai Mitko still had a plan B.",
  "look.apartment.table": "A table for bills, promises, and other paper tragedies.",
  "look.apartment.rakia_bottle": "Homemade rakia. No label, because truth needs no paperwork.",
  "look.apartment.bed": "A sofa-bed. Coalition by day, governing majority by night.",
  "msg.apartment.nap": "Bai Mitko took an official nap. The world has one horizon again.",
  "msg.apartment.window_opened": [
    "Mmmm. Smells like elections.",
    "Someone must have aired out the coalition again."
  ],
  "msg.apartment.window_closed": "That is enough fresh air. We might end up with a draft.",
  "look.apartment.poster": "VOTE MITKO: AT LEAST YOU KNOW HIM. A strong platform when the village has run out of options.",
  "look.square.poster_board": "Poster over poster over promise. Archaeology of hope.",
  "look.square.fountain": "The fountain does not work, but at least it is not stealing electricity.",
  "look.square.kiosk": "The kiosk knows more news than it sells.",
  "look.square.empty_envelope": "An empty envelope fallen from the kiosk. No address, but plenty of official confidence.",
  "look.square.statue": "A monument to a local hero from the bust upward. Below that, the budget ran out.",
  "look.square.old_men_bench": "The bench is the only polling institute with a permanent sample.",
  "look.square.election_notice": "It says the election is transparent. The paper looks slightly cloudy.",
  "look.square.mehana_menu": "The menu is laminated so the prices cannot soak away.",
  "look.dropped_items": "The bag holds {count} abandoned decisions. Unlike Bai Mitko, it loses nothing.",
  "look.mehana.oil": "Sunflower oil. In this country, both salad and careers slide on it.",
  "look.mehana.water_jug": "Water. The most dangerous liquid in the tavern because it raises suspicion.",
  "look.mehana.table": "Bai Mitko has taken a seat with the confidence of a man whose bill belongs to the next administration.",
  "look.mehana.bai_mitko_rakia_glass": "This is the glass Tony watches like an election committee with a personal grudge.",
  "look.mehana.tony_rakia_glass": "Rakia to the rim. With Tony, transparency always comes at high proof.",
  "look.mehana.cellar_hatch": "A cellar hatch secured by habit rather than a lock.",
  "look.mehana.ballot_box": "The ballot box is transparent so everyone can see how cloudy the situation is.",
  "look.mehana.newspaper": "The paper says the street has been repaired on paper. Bai Mitko looks outside. Apparently the paperwork took a different road.",
  "look.mehana.radio": "The radio says there is no crisis—the situation has merely been reclassified as a difficulty. Bai Mitko respects exact science.",
  "look.npc.mehana_waiter": "Kiro remembers every order and forgets every request for a receipt.",
  "look.npc.baba_stoyanka": "Baba Stoyanka looks like she survived three regimes and four renovations of the square.",
  "look.npc.tony_fridge": "Tony the Fridge. A man with the back of a wardrobe and the liver of a municipal budget.",
  "look.municipality.candidate_register": "The register has a column for qualifications and three columns explaining why the first column is mandatory.",
  "look.municipality.stamp_desk": "The stamp desk is lit like an altar. Without a stamp, a document is only an opinion.",
  "look.municipality.archive_cabinet": "The archive stores documents, jars, and secrets in the same format.",
  "look.npc.municipality_clerk": "Clerk Penka has aligned every paper on her desk except the one the citizen actually needs.",
  "look.npc.municipality_colleague": "The colleague is closely observing the work in case it gets away.",
  "talk.npc.municipality_clerk.busy": "Can't you see I'm busy right now?",
  "talk.npc.municipality_colleague.helping": "I'm assisting my colleague at the moment.",
  "talk.npc.municipality_security_officer.identification": "Identification. If you don't have any, at least try to look convincing.",
  "look.npc.municipality_security_officer": "The duty officer protects the municipality from anything not entered in the logbook.",
  "look.npc.journalist": "Ralitsa holds her microphone like a title deed to somebody else's discomfort.",
  "hotspot.election_booth.commission_table.name": "Election commission table",
  "look.election_booth.commission_table": "Three members guard two protocols and a pen tied to the state with string.",

  "msg.walk": "Bai Mitko walks like a man who owes money in three directions.",
  "msg.no_use": "Morally questionable, administratively impossible.",
  "msg.taken": "Taken. This looks useful, or at least deniable.",
  "msg.already_taken": "Already pocketed. Bai Mitko does not repeat theft without a reason.",
  "msg.inventory.dropped_nearby": "Bai Mitko left {item} nearby. He can retrieve it if bureaucracy demands.",
  "msg.inventory.picked_up_again": "{item} is back in Bai Mitko's pockets.",
  "msg.inventory.cannot_use_with": "{item} does not work with {target}.",
  "msg.inventory.npc_reject_generic": "Do not involve me in that. I am involved in quite enough already.",
  "msg.inventory.npc_reject.baba_stoyanka": "Don't palm that off on me, lad. I'm a person, not a municipal storeroom.",
  "msg.inventory.npc_reject.journalist": "That has nothing to do with the interview. Which makes it suspiciously relevant, but no.",
  "msg.inventory.npc_reject.mehana_waiter": "You bring an order to a table, not whatever is weighing down your pockets.",
  "msg.inventory.npc_reject.tony_fridge": "No. That lacks the capacity for my table.",
  "msg.inventory.npc_reject.municipality_clerk": "That object has no incoming reference number for me. Return it to its holder.",
  "msg.inventory.cannot_combine": "{item} and {target} refuse to form a coalition.",
  "msg.inventory.cannot_use_on_self": "Bai Mitko finds no personal application for {item}.",
  "msg.need_talk": "That is not a conversation. That is infrastructure.",
  "msg.scene_saved": "Saved.",
  "msg.mehana.rakia_ordered": "A rakia arrives. The glass is small, but its mandate is strong.",
  "msg.rakia.level.daisy": "To your health. And to quorum.",
  "msg.rakia.level.merry": "Now my platform has finally grown broader.",
  "msg.rakia.level.tipsy": "I am not swaying. The coalition keeps moving the floor.",
  "msg.rakia.level.plastered": "Quiet! I am negotiating with the wardrobe.",
  "msg.water_recovery": "Water performs no miracles, but Bai Mitko at least remembers which floor is his.",
  "msg.self.water": "Bai Mitko drank the water. The world lost one degree and half an argument.",
  "msg.self.tripe_soup": "The tripe soup removed two degrees from Bai Mitko and three layers of paint from the jar.",
  "msg.self.shopska": "The Shopska absorbed some of the alcohol. The cheese claimed the credit.",
  "msg.self.rakia": "Bai Mitko drank the bottle on official business. The campaign immediately became more convincing than the floor.",
  "msg.self.village_wine": "The village wine added one degree and a distant memory of a community-hall dance.",
  "msg.self.accordion": "Bai Mitko played the old tune to himself. The memories returned. The money did not.",
  "msg.self.sunflower_oil": "Bai Mitko drank the oil. His internal policy now moves without friction.",
  "msg.mehana.tripe_soup": "The tripe soup arrives like a warm parliamentary committee. Bai Mitko regains a few percentage points.",
  "msg.mehana.shopska_ordered": "The Shopska arrives under a landslide of cheese. The tomatoes request observer status.",
  "msg.mehana.rakia_to_go": "Kiro wraps the rakia for travel, legally converting it from a drink into luggage.",
  "msg.mehana.shopska_to_go": "Kiro seals the Shopska in a box. The cheese is now travelling on official business.",
  "msg.mehana.tripe_soup_to_go": "The tripe soup enters a jar. The smell refuses to sign the transfer papers.",
  "msg.mehana.village_wine": "Kiro pours the village wine. It has notes of barrel, elections, and a distant cousin.",
  "msg.mehana.village_wine_to_go": "Kiro hands over an unlabelled bottle. This keeps the contents politically independent.",
  "msg.oil_used": "Bai Mitko drank the oil with the expression of a man investing in the future.",
  "msg.accordion_tony": "Tony closed his eyes and joined in harmony. A waitress from 1998 had temporarily suspended supervision of the glass.",
  "msg.accordion_baba_before_vote": "Baba Stoyanka: That took me back to a village dance, when my knees still had quorum. Lovely playing. Now make the fountain sing too.",
  "msg.accordion_baba_after_vote": "Baba Stoyanka: Play now. You already have my vote, but my youth still owes me one dance.",
  "msg.accordion_kiro": "Kiro: Keep playing and I charge for live music. Stop and I charge a quietness fee.",
  "msg.accordion_animal": "The animal listened, tilted its head, and declined to disclose its political preferences.",
  "msg.accordion_generic_npc": "The old tune found somebody's memory. They declined to specify the year or marital status.",
  "msg.water_swap_ready": "While Tony sang, Bai Mitko replaced the rakia in his own glass with water. Oversight had become musical.",
  "msg.water_swap_watched": "Tony: Water in your glass? You have not distracted the supervisory authority yet.",
  "msg.water_swap_still_watched": "Tony is still watching the glass. Repetition does not make the trick more legal.",
  "msg.water_tony_wrong_glass": "That is Tony's glass. Tampering with the opponent's rakia belongs to a different criminal statute.",
  "msg.tony.gift_not_vote": "Tony: I accept treats after the vote. Before the vote it is influence, and I insist influence be alcoholic and equal-opportunity.",
  "msg.kiro.return_purchase": "Kiro: Giving a purchase back counts as a reverse delivery. That needs a new receipt and a larger bill.",
  "msg.fake_diploma.assembled": [
    "Bai Mitko folded the most official-looking overdue bill into the envelope and reclassified the red OVERDUE notice as an academic seal.",
    "A diploma in Local Government and Applied Persuasion. The course was correspondence-only because it never took place."
  ],
  "msg.municipality.credentials_accepted": "Penka inspected the margins, respected the envelope, and accepted the diploma without troubling its contents. The register still needs the self-service stamp.",
  "msg.municipality.credentials_already_accepted": "The diploma is already registered. Showing it twice would create a second original.",
  "msg.municipality.register_needs_stamp": "The candidate exists in pencil. A municipal stamp would make the condition permanent.",
  "msg.municipality.register_stamped": "THUNK. The register now believes in Bai Mitko more strongly than most voters do.",
  "msg.municipality.register_ready": "The entry is stamped. The ink has granted it administrative reality.",
  "msg.municipality.archive_credentials_first": "The archive cabinet refuses informal relationships. Candidate credentials come first.",
  "msg.municipality.archive_stamp_first": "Penka: First bring me the diploma validated by the Mayor. Once I register you, you can check the archive.",
  "msg.municipality.ballot_box_clue": "The ballot box is in this archive cabinet, filed under transparent containers for seasonal use.",
  "msg.municipality.ballot_box_clue_repeat": "The ballot box is filed in the municipal archive under transparent seasonal containers.",
  "msg.mehana.cellar_no_reason": "Bai Mitko has no official reason to inspect Kiro's cellar. Personal curiosity has standards.",
  "msg.mehana.cellar_opened": "The hatch opens. Behind two pickle jars sits the missing ballot box, preserving democracy at room temperature.",
  "msg.mehana.cellar_already_open": "The cellar is open. The pickles remain under informal supervision.",
  "msg.mehana.ballot_box_recovered": "Bai Mitko recovered the ballot box. It smells faintly of dill, but the seal has survived.",
  "msg.scene_not_ready": "This part of the municipality is still under repair of the repair.",

  "quest.chapter1.main.title": "Become Mayor before your creditors find you.",
  "quest.chapter1.fake_diploma.title": "Create a diploma impressive enough for voters who never read diplomas.",
  "quest.chapter1.fake_diploma.stage.collect_official_paper": "Find paper that already looks sufficiently official.",
  "quest.chapter1.fake_diploma.stage.collect_envelope": "Take the bills to the kiosk for a diploma, or find an empty envelope there to assemble one yourself.",
  "quest.chapter1.fake_diploma.stage.assemble": "Give the bills to the kiosk, or combine them with the empty envelope.",
  "quest.chapter1.baba_vote.title": "Repair the fountain and earn Baba Stoyanka's support.",
  "quest.chapter1.tony_vote.title": "Win Tony the Fridge's support without losing consciousness.",
  "quest.chapter1.tony_vote.stage.accept_challenge": "Accept Tony the Fridge's drinking challenge.",
  "quest.chapter1.tony_vote.stage.distract": "Find a way to distract Tony during the challenge.",
  "quest.chapter1.tony_vote.stage.swap_water": "Replace the rakia in Bai Mitko's glass with water.",
  "quest.chapter1.tony_vote.stage.finish_challenge": "Finish Tony's drinking challenge.",
  "quest.chapter1.journalist.title": "Survive the journalist's questions without accidentally telling the truth.",
  "quest.chapter1.journalist.stage.find_reporter": "Return to the square and find the journalist by the election notice.",
  "quest.chapter1.journalist.stage.finish_interview": "Finish the interview before the facts arrive.",
  "quest.chapter1.ballot_box.title": "Find the missing ballot box before someone ferments democracy.",
  "quest.chapter1.ballot_box.stage.follow_archive_clue": "Inspect the jammed drawer; use the accordion strap to open it.",

  "dialogue.common.back": "Back.",
  "dialogue.municipality_clerk.start": "Clerk Penka: Candidate registration. Documents first; personhood is verified later if the schedule permits.",
  "dialogue.municipality_clerk.choice.present_credentials": "Present my candidate credentials.",
  "dialogue.municipality_clerk.choice.ask_registration": "Register me as a candidate.",
  "dialogue.municipality_clerk.choice.registration_status": "Are my credentials in order?",
  "dialogue.municipality_clerk.choice.leave": "I will return with more paper.",
  "dialogue.municipality_clerk.credentials_missing": "Clerk Penka: I need proof of higher education. The municipality may already have it, but asking itself would require an interdepartmental envelope.",
  "dialogue.municipality_clerk.credentials_accepted": "Clerk Penka: The typeface is confident, the red mark is official-looking, and the envelope shows institutional experience. Accepted.",
  "dialogue.municipality_clerk.credentials_registered": "Clerk Penka: Your credentials are entered. Take the stamp from the self-service desk and stamp the candidate register. Reform means citizens now obstruct themselves.",
  "dialogue.municipality_clerk.registration_stamped": "Clerk Penka: You are registered. The archive cabinet is now permitted to remember you.",
  "dialogue.square.mehana_menu.title": "MEHANA “THE TWO GOATS” — TODAY'S MENU",
  "dialogue.square.mehana_menu.food_heading": "FOOD",
  "dialogue.square.mehana_menu.meatballs": "Public Procurement Meatballs — two on paper, one on the plate.",
  "dialogue.square.mehana_menu.shopska": "Full Transparency Shopska — everything is hidden under cheese.",
  "dialogue.square.mehana_menu.mash": "Renovation-of-the-Renovation Mash — yesterday's potato with a fresh patch.",
  "dialogue.square.mehana_menu.drinks_heading": "DRINKS",
  "dialogue.square.mehana_menu.rakia": "Caretaker Rakia — temporary until made permanent.",
  "dialogue.square.mehana_menu.wine": "Good-Neighbour Wine — repairs relations, not causes.",
  "dialogue.square.mehana_menu.beer": "Coalition Beer — two bottles sharing one glass.",
  "dialogue.square.mehana_menu.water": "Minority Water — nobody orders it.",
  "dialogue.square.mehana_menu.close": "Close menu",
  "dialogue.waiter.start": "Kiro: The menu is advisory. The bill is final.",
  "dialogue.waiter.choice.rakia": "One rakia.",
  "dialogue.waiter.choice.shopska": "One Shopska salad.",
  "dialogue.waiter.choice.tripe_soup": "Tripe soup for stabilization.",
  "dialogue.waiter.choice.village_wine": "A bottle of the village wine.",
  "dialogue.waiter.choice.tony_weakness": "Does Tony always watch other people's glasses like that?",
  "dialogue.waiter.serving_question": "Kiro: Having it here or taking it with you?",
  "dialogue.waiter.choice.for_here": "For here. Immediate consumption.",
  "dialogue.waiter.choice.to_go": "To go. Pack it up.",
  "dialogue.waiter.choice.people": "Who else is drinking here?",
  "dialogue.waiter.choice.leave": "I am only inspecting the prices.",
  "dialogue.waiter.people": "Kiro: Tony drinks at the large table. The others form a temporary coalition around whoever is paying.",
  "dialogue.waiter.tony_weakness": "Kiro: Only while he is awake. Play an old wedding tune and he closes his eyes over a snack-bar waitress named Snezhana from 1998. You could carry the till past him then.",
  "dialogue.tony.start": "Tony: Speak. My glass is listening.",
  "dialogue.tony.choice.challenge": "Let's discuss the glasses.",
  "dialogue.tony.choice.challenge_status": "Why are you watching my glass?",
  "dialogue.tony.choice.finish_challenge": "Let us finish this demonstration of capacity.",
  "dialogue.tony.choice.confirm_support": "So your vote is mine?",
  "dialogue.tony.choice.politics": "Tony, the village needs stability.",
  "dialogue.tony.choice.leave": "I'll stabilize from outside.",
  "dialogue.tony.politics": "Tony: Stability is in the fridge. You open it, it is still cold.",
  "dialogue.tony.challenge": "Tony: Two identical glasses. We drink equally. Whoever quits campaigns for the old mayor. And I watch your glass—this is an election, so there must be oversight.",
  "dialogue.tony.choice.accept": "I accept. My liver is coalition-ready.",
  "dialogue.tony.choice.refuse": "Not yet. I need campaign preparation.",
  "dialogue.tony.challenge_accepted": "Tony: Kiro, two rakias. Identical ones—do not let democracy interfere.",
  "dialogue.tony.challenge_deferred": "Tony: Go and prepare. I do not start a vote without quorum or drinking without a candidate.",
  "dialogue.tony.choice.prepare": "I will return with the required capacity.",
  "dialogue.tony.challenge_waiting": "Tony: I am watching yours. Mine knows its job.",
  "dialogue.tony.contest_result": "Tony drained his rakia. Bai Mitko drank the water with heroic suffering. Tony: You held up. Liver or procedure—local government accepts both. You have my vote.",
  "dialogue.tony.support_confirmed": "Tony: It is yours. Do not make me repeat myself—repetition is for drinking, not politics.",
  "dialogue.baba.start": "Baba Stoyanka: You are all crooks, but some of you at least say hello.",
  "dialogue.baba.choice.ask_vote": "Let's discuss your vote.",
  "dialogue.baba.choice.tradition": "My corruption is traditional.",
  "dialogue.baba.choice.promise": "I will renovate the renovation.",
  "dialogue.baba.choice.offer_bills": "I brought unpaid bills. A document of the people.",
  "dialogue.baba.choice.offer_water": "A glass of water. Pure as my intentions.",
  "dialogue.baba.choice.offer_shopska": "A Shopska salad. Heavy with national responsibility.",
  "dialogue.baba.choice.offer_tripe_soup": "Tripe soup. It restores public confidence.",
  "dialogue.baba.choice.offer_rakia": "A bottle of rakia. For pre-election understanding.",
  "dialogue.baba.choice.offer_oil": "A bottle of sunflower oil. Traditional and manifesto-free.",
  "dialogue.baba.choice.offer_wine": "A bottle of wine. For diplomatic repairs.",
  "dialogue.baba.choice.confirm_vote": "Your vote is still mine, right?",
  "dialogue.baba.choice.leave": "I'll come back, unless they find me first.",
  "dialogue.baba.tradition": "Baba Stoyanka: Traditional, you say? Then at least leave something for the children.",
  "dialogue.baba.vote_terms": "Baba Stoyanka: Bring something useful before asking for my vote. I already have enough promises canned for winter.",
  "dialogue.baba.promise": "Baba Stoyanka: They have been renovating that renovation since my goat was young.",
  "dialogue.baba.vote_confirmed": "Baba Stoyanka: It is yours. Do not make me repeat myself—the price will go up.",
  "msg.baba.reject_bills": "Baba Stoyanka: Mine are filed better. You cannot buy a vote with somebody else's debt—only anxiety.",
  "msg.baba.reject_water": "Baba Stoyanka: The tap is twenty paces away. You even want the municipality to fund the bribe.",
  "msg.baba.reject_shopska": "Baba Stoyanka: No bread, no rakia, and already warm. That is not a bribe. That is leftovers.",
  "msg.baba.reject_tripe_soup": "Baba Stoyanka: Cold tripe soup is for an enemy, not a voter.",
  "msg.baba.reject_rakia": "Baba Stoyanka: Rakia? I distil my own. Shop-bought rakia only buys you a headache.",
  "msg.baba.accept_oil": "Baba Stoyanka: At least that belongs in a cooking pot. You have my vote, but I am keeping my shopping bag.",
  "msg.baba.reject_late_oil": "Baba Stoyanka: Three insults ago, that would have worked. Now the oil only covers interest. Bring wine—not for my vote, for diplomatic repairs.",
  "msg.baba.reject_early_wine": "Baba Stoyanka: Wine is for mending relations. We have not quarrelled properly yet. Bring sunflower oil.",
  "msg.baba.accept_wine": "Baba Stoyanka: Now you sound like a man who understands the tariff. You have my vote. For the last time until the next election.",

  "dialogue.journalist.start": "Ralitsa Microphonova: Bai Mitko, three short questions. The questions are short; the consequences are not.",
  "dialogue.journalist.choice.begin": "Go ahead. My truth is on administrative leave.",
  "dialogue.journalist.choice.continue": "Let us continue before I remember anything.",
  "dialogue.journalist.choice.result": "So how did the interview go?",
  "dialogue.journalist.choice.leave": "No more questions for now.",
  "dialogue.journalist.roads": "Ralitsa: The streets are mostly potholes with connecting asphalt. What will you do as councillor?",
  "dialogue.journalist.roads.choice.heritage": "Declare them immovable cultural heritage. At least then they will be protected.",
  "dialogue.journalist.roads.choice.inventory": "First, a complete inventory. Then repairs in alphabetical pothole order.",
  "dialogue.journalist.roads.choice.drive_around": "I avoid them successfully. We will train the public.",
  "dialogue.journalist.complaints": "Ralitsa: Residents say their complaints disappear inside the municipality. How will you restore trust?",
  "dialogue.journalist.complaints.choice.counted": "Every complaint will be counted precisely. Solving them is a separate procurement.",
  "dialogue.journalist.complaints.choice.one_stop": "One service desk. It will send people back to itself, saving them the walk.",
  "dialogue.journalist.complaints.choice.not_ours": "If it disappeared, it is clearly outside our jurisdiction—and underwater.",
  "dialogue.journalist.ballot_box": "Ralitsa: The ballot box was stored with the pickles. Who is responsible?",
  "dialogue.journalist.ballot_box.choice.pickles": "It was stored transparently. The gherkins were the only witnesses.",
  "dialogue.journalist.ballot_box.choice.responsibility": "Responsibility completed the full circuit and has returned to the first responsible office.",
  "dialogue.journalist.ballot_box.choice.training": "The ballot box was attending field training in local tradition.",
  "dialogue.journalist.complete": "Ralitsa: Excellent. You answered nothing exactly, but everything confidently. My report is ready, and the polling station is open.",

  "ui.election.commit_confirm": "This starts the final count and closes unfinished campaign errands. Should Bai Mitko stand for election?",
  "msg.election.deferred": "The commission will wait. For once today, the citizen chose the delay.",
  "msg.election.not_ready": "The commission cannot find a legal basis for counting this state of affairs.",
  "ending.chapter1.complete": "Chapter 1 complete",
  "ending.chapter1.convincing_win.title": "A convincing victory by local standards",
  "ending.chapter1.convincing_win.body": "Bai Mitko wins by a majority clear enough to survive three recounts. The old mayor congratulates the procedure without congratulating the winner. The ballot box returns to the municipality, and the pickles receive a certificate for civic courage.",
  "ending.chapter1.narrow_win.title": "A victory one official stamp thick",
  "ending.chapter1.narrow_win.body": "Bai Mitko wins by one vote and half an invalid ballot that occupies the commission until evening. The old mayor leaves to appeal the direction of the wind. The village accepts the result because the Mehana has opened.",
  "ending.chapter1.loss.title": "An honourable loss recorded as an attempt",
  "ending.chapter1.loss.body": "Bai Mitko loses, but earns enough votes to be registered as a local phenomenon. The commission gives him a copy of the protocol without its final page. The campaign ends; the unpaid bills begin another independent term."
};
